config/routes.rb
Rails.application.routes.draw do

  get 'dishes/admin' => 'dishes#admin'

  resources :dishes do
    resources :orders, only: [:new, :create]
  end
  resources :orders, only: [:index, :show, :edit, :update, :destroy]

end

app/models/dish.rb
class Dish < ActiveRecord::Base
    has_many :orders, inverse_of: :dish
    validates :dish_name, :price, :stock, :restaurant, :ImageURL, presence: true
end

app/models/order.rb
class Order < ActiveRecord::Base
    belongs_to :dish
    validates :dish, presence: true
    validates :phone_num, presence: true
    validates :phone_num, format: { with: /[0-9]{8}/, message: "Not a valid HK Phone Number" }
    validate :order_amount_cannot_exceeds_dish_stock
    def order_amount_cannot_exceeds_dish_stock
      if dish.orders.size > dish.stock
        errors[:base] << "This dish has been sold out !"
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :set_dish, only: [:show, :edit, :update, :destroy]

  def admin
    @dishes = Dish.all
  end
  # GET /dishes
  # GET /dishes.json
  def index
    @dishes = Dish.all
  end

  # GET /dishes/1
  # GET /dishes/1.json
  def show
  end

  # GET /dishes/new
  def new
    @dish = Dish.new
  end

  # GET /dishes/1/edit
  def edit
  end

  # POST /dishes
  # POST /dishes.json
  def create
    @dish = Dish.new(dish_params)

    respond_to do |format|
      if @dish.save
        format.html { redirect_to @dish, notice: 'Dish was successfully created.' }
        format.json { render :show, status: :created, location: @dish }
      else
        format.html { render :new }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dishes/1
  # PATCH/PUT /dishes/1.json
  def update
    respond_to do |format|
      if @dish.update(dish_params)
        format.html { redirect_to dishes_admin_path, notice: "Dish #{@dish.dish_name} was successfully updated." }
        format.json { render :show, status: :ok, location: @dish }
      else
        format.html { render :edit }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dishes/1
  # DELETE /dishes/1.json
  def destroy
    @dish.destroy
    respond_to do |format|
      format.html { redirect_to dishes_url, notice: 'Dish was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dish
      @dish = Dish.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dish_params
      params.require(:dish).permit(:dish_name, :price, :stock, :restaurant, :restaurantURL, :ImageURL)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new(:time=>Time.new)
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create

    @dish = Dish.find(params[:dish_id])
    @order = @dish.orders.new(order_params)
    ctime = Time.now
    @order.time = ctime.strftime("%Y-%m-%d %H:%M:%S")

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render "errors" , :locals=>{:order=>@order} }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_path, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:dish_id, :name, :phone_num, :time)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dishes/_form.html.erb
<%= form_for(@dish) do |f| %>
  <% if @dish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dish.errors.count, "error") %> prohibited this dish from being saved:</h2>

      <ul>
      <% @dish.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :restaurant %><br>
    <%= f.text_field :restaurant %>
  </div>
  <div class="field">
    <%= f.label :restaurant_URL %><br>
    <%= f.text_field :restaurantURL %>
  </div>
  <div class="field">
    <%= f.label :dish_name %><br>
    <%= f.text_field :dish_name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :stock %><br>
    <%= f.number_field :stock %>
  </div>
  <div class="field">
    <%= f.label :Image_URL %><br>
    <%= f.text_field :ImageURL %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dishes/admin.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing dishes</h1>

<table>
  <thead>
    <tr>
      <th>Restaurant</th>
      <th>Dish name</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dishes.each do |dish| %>
      <tr>
        <td><%= dish.restaurant %></td>
        <td><%= dish.dish_name %></td>
        <td><%= dish.price %></td>
        <td><%= link_to 'Show', dish %></td>
        <td><%= link_to 'Edit', edit_dish_path(dish) %></td>
        <td><%= link_to 'Destroy', dish, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dish', new_dish_path %> |
<%= link_to 'Check the Orders', orders_path %> |
<%= link_to 'Goto Menu Page', dishes_path %>

app/views/dishes/edit.html.erb
<p id="notice"><%= notice %></p>

<h1>Editing dish</h1>

<%= render 'form' %>

<%= link_to 'Back', dishes_admin_path %>

app/views/dishes/index.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel">


      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>   
        <li data-target="#myCarousel" data-slide-to="1"></li>
      </ol>

      <div id="myCarousel-inner" class="carousel-inner">


        <div class="item active">
          <%= link_to image_tag(@dishes.first.ImageURL), @dishes.first %>
          <div class="container">
            <div class="carousel-caption">
              
            <table class="table transbox table-short">
              <tbody>
                <tr>
                    <td><p><%= @dishes.first.dish_name %> @ <%= link_to @dishes.first.restaurant, @dishes.first.restaurantURL, :class=>'a' %></p></td>
                </tr>
                <tr>
                    <td><p><%= @dishes.first.price %> HKD</p></td>
                </tr>

              </tbody>
            </table>

              <div class="col-sm-offset-4 col-sm-4">
                  <p>还剩<%=@dishes.first.stock - @dishes.first.orders.size%>份
              <%= link_to '就要这个', @dishes.first, class: "btn btn-lg btn-danger btn-block", role: "button", style: 'color:white;' %></p>
              </div>
            </div> 
          </div>
        </div>

        <% @dishes.drop(1).each do |dish| %>
          <div class="item">
            <div class="text-center">
            <%= link_to image_tag(dish.ImageURL), dish %>
            </div>
            <div class="container">
              <div class="carousel-caption">

              <table class="table transbox table-short">
                <tbody>
                  <tr>
                      <td><p><%= dish.dish_name %> @ <%= link_to dish.restaurant, dish.restaurantURL%></p></td>
                  </tr>
                  <tr>
                      <td><p><%= dish.price %> HKD</p></td>
                  </tr>

                </tbody>
              </table>

              <div class="col-sm-offset-4 col-sm-4">
                  <p>还剩<%=dish.stock - dish.orders.size %>份
              <%= link_to '就要这个', dish, class: "btn btn-lg btn-danger btn-block", role: "button", style: 'color:white;' %></p>
              </div>
             

              </div>
            </div>
          </div>
        <% end %>

      </div>
    
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>


    </div><!-- /.carousel -->
<!--
<h1>Listing dishes</h1>
<p> Click on the dish you like to order !</p>
<table>
  <tbody>
    <tr>
      <% @dishes.each do |dish| %>
        <td colspan="3"><%= link_to image_tag(dish.ImageURL, size: "200x180"), dish %></td>
      <% end %>
    </tr>
    <tr>
      <% @dishes.each do |dish| %>
        <td><%= link_to dish.restaurant, dish.restaurantURL %></td>
        <td><%= dish.dish_name %></td>
        <td><%= dish.price %></td>
      <% end %>
    </tr>
    <tr>
      <% @dishes.each do |dish| %>
        <td colspan="3">Stock:   <%=dish.orders.size %>/<%= dish.stock %></td>
      <% end %>
    </tr>
  </tbody>
</table>

<br>
-->

app/views/dishes/new.html.erb
<h1>New dish</h1>

<%= render 'form' %>

<%= link_to 'Back', dishes_path %>

app/views/dishes/show.html.erb
<div id="bg">
  <%= image_tag(@dish.ImageURL, class: "img-blur") %>
</div>



<div class="container bottom">




             <table class="table transbox table-width">
                <tbody>
                  <tr>
                    <td colspan=2><div class="text-center"><h1>订单详情</h1></div></td>       
                  </tr>
                  <tr>
                    <td><p>时间</p></td>                    
                    <td><p>正午 12:00</p></td>
                  </tr>
                  <tr>
                    <td><p>地点</p></td> 
                    <td><p>开心公园</p></td>
                  </tr>                  
                  <tr>
                    <td><p>菜品</p></td>
                    <td><p><%= @dish.dish_name %> @ <%= link_to @dish.restaurant, @dish.restaurantURL %></p></td>
                  </tr>
                  <tr>
                    <td><p>价格</p></td> 
                    <td><p><%= @dish.price %> HKD</p></td>
                  </tr>

                </tbody>
             </table>


<%= render "orders/form" %>
</div>
<!--
 <form class="form-horizontal" role="form">

    <div class="form-group">
        <label class="col-sm-5 control-label text-white">Restaurant</label> 
        <p class="col-sm-5 text-align-left large-font-size"><%= @dish.restaurant %></p> 
    </div>

    <div class="form-group">
        <label class="col-sm-5 control-label text-white">Dish name</label> 
        <p class="col-sm-5 text-align-left large-font-size"><%= @dish.dish_name %></p> 
    </div>

    <div class="form-group">
       <label class="col-sm-5 control-label text-white">Price</label> 
        <p class="col-sm-5 text-align-left large-font-size"><%= @dish.price %></p> 
    </div>
 </form>
</div>


<p>
  <strong>Restaurant:</strong>
  <%= @dish.restaurant %>
</p>

<p>
  <strong>Dish name:</strong>
  <%= @dish.dish_name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @dish.price %>
</p>
-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Foodrocks</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <%= link_to image_tag("logoo.jpg", size: "200x51"), dishes_path, class: "navbar-brand"%>


          <ul class="nav navbar-nav">
           <li class="active"><%= link_to '菜品', dishes_path %></li>
           <li><a href="#">订餐流程</a></li>
           <li><a href="#">反馈</a></li>
          </ul>

        </div>
        
      </div>
    </div>
    
<%= yield %>

</body>
</html>

app/views/orders/_form.html.erb
<%= form_for([@dish, @dish.orders.build], html:{class: "form-horizontal "}) do |f| %>

  <div class="field">
    <%= f.hidden_field :dish_id %>
  </div>



  <div class="field form-group">
    <%= f.label "手机号码", :class=>'col-sm-5 control-label text-white '%>

    <div class="col-sm-3">
      <%= f.number_field :phone_num, :class=>'form-control' %>
    </div>
  </div>





<div class="actions col-sm-offset-3 col-sm-6">
<a href="#modal-dialog" class="modal-toggle btn btn-lg btn-danger btn-block" data-toggle="modal" data-href="http://localhost.testing/modal-processing.php" data-modal-type="confirm" data-modal-title="Delete Property" data-modal-text="Are you sure you want to delete {$property.address_string}?" data-modal-confirm-url="{$base_url}residential-lettings/properties/do-delete/property/{$property.id}"><i class="icon-trash"></i>落单</a>
</div>

  <div class="actions col-sm-offset-3 col-sm-6">
    <%= link_to "返回", dishes_path, style: 'color:white;' %>
  </div>

<div id="modal-dialog" class="modal">
  <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
            <a href="#" data-dismiss="modal" aria-hidden="true" class="close">×</a>
            <div class="text-center"><img src="../assets/logoo.jpg"></div>

        </div>
             <div class="text-center"><h1>确认落单</h1></div>

             <table class="table table-striped">
                <tbody class="table-comfirmed">
                  <tr>
                    <td><p>手机号码</p></td>                    
                    <td><p>？？？？</p></td>
                  </tr>
                  <tr>
                    <td><p>时间</p></td>                    
                    <td><p>正午 12:00</p></td>
                  </tr>
                  <tr>
                    <td><p>地点</p></td> 
                    <td><p>开心公园</p></td>
                  </tr>                  
                  <tr>
                    <td><p>菜品</p></td>
                    <td><p><%= @dish.dish_name %> @ <%= link_to @dish.restaurant, @dish.restaurantURL %></p></td>
                  </tr>
                  <tr>
                    <td><p>价格</p></td> 
                    <td><p><%= @dish.price %> HKD</p></td>
                  </tr>

                </tbody>
            </table>    

        <div class="modal-footer">
          <%= f.submit "确认", :class=>'btn btn-lg btn-danger btn-block'%>
          <a href="#" data-dismiss="modal" aria-hidden="true" class="btn btn-lg btn-default btn-block">返回</a>
        </div>
      </div>
    </div>
</div>  


<% end %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/errors.html.erb
<% if order.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>
    <ul>
    <% order.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= link_to 'Back to Menu', dishes_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing orders</h1>
<table>
  <thead>
    <tr>
      <th>Time</th>
      <th>Dish</th>
      <th>Phone num</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.time %></td>
        <td><%= order.dish.dish_name %></td>
        <td><%= order.phone_num %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'Check the Dishes', dishes_admin_path %> |
<%= link_to 'Goto Menu Page', dishes_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>

  <strong>The Dish you ordered is:</strong>
  <%= @order.dish.dish_name %>
</p>

<p>
  <strong>Your Phone Number (Used to pick up):</strong>
  <%= @order.phone_num %>
</p>

<%= link_to 'Back to Menu', dishes_path %>